apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: demoapp
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./demo_pods
  prune: true
  sourceRef:
    kind: GitRepository
    name: demoapp
  targetNamespace: default