---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: demo-pods
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/jcedmonson/demo-infra

